models.py
from app import db
from app import app
from datetime import datetime


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(length=100), nullable=False, unique=True)
    password = db.Column(db.String(length=100), nullable=False)
    blogs = db.relationship('Post')

    def __int__(self, username, password):
        self.username = username
        self.password = password


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(length=100), db.ForeignKey(User.username), nullable=True)
    created = db.Column(db.DateTime, nullable=False)
    title = db.Column(db.Text, nullable=False)
    body = db.Column(db.Text, nullable=False)

    def __init__(self, username, title, body):
        self.username = username
        self.title = title
        self.body = body
        self.created = datetime.now()

    def update_post(self, title, body):
        self.title = title
        self.body = body
        db.session.commit()


def init_db():
    with app.app_context():
        db.drop_all()
        db.create_all()

blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    body = TextAreaField(validators=[DataRequired()])
    submit = SubmitField()

users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, NoneOf, Length, ValidationError
from users.validation import *


class RegisterForm(FlaskForm):
    username = StringField(validators=[DataRequired(), Email(), character_check])
    password = PasswordField(validators=[DataRequired(), Length(min=8, max=15), character_check, validate_number, validate_lowercase])
    confirm_password = PasswordField(validators=[DataRequired(), validate_password])
    submit = SubmitField()


class LoginForm(FlaskForm):
    username = StringField(validators=[DataRequired(), Email()])
    password = PasswordField(validators=[DataRequired()])
    submit = SubmitField()

app.py
import os
from flask import Flask, render_template
from dotenv import load_dotenv
from flask_sqlalchemy import SQLAlchemy


load_dotenv()

app = Flask(__name__)
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('SQLALCHEMY_DATABASE_URI')
app.config['SQLALCHEMY_ECHO'] = os.getenv('SQLALCHEMY_ECHO') == 'True'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = os.getenv('SQL_TRACK_MODIFICATIONS') == 'True'
db = SQLAlchemy(app)

from main.views import main_blueprint
from blog.views import blog_blueprint
from users.views import users_blueprint

app.register_blueprint(main_blueprint)
app.register_blueprint(blog_blueprint)
app.register_blueprint(users_blueprint)


@app.errorhandler(403)
def function_name(error):
    return render_template('403.html'), 403


@app.errorhandler(404)
def function_name(error):
    return render_template('404.html'), 404


@app.errorhandler(500)
def function_name(error):
    return render_template('500.html'), 500




if __name__ == '__main__':
    app.run()

blog/views.py
from flask import Blueprint, render_template
from app import db
from blog.forms import PostForm
from models import Post
from sqlalchemy import desc

blog_blueprint = Blueprint('blog', __name__, template_folder='template')


@blog_blueprint.route('/blog')
def blog():
    posts = Post.query.order_by(desc('id')).all()
    return render_template('blog/blog.html', posts=posts)


@blog_blueprint.route('/create', methods=('GET', 'POST'))
def create():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(username=None, title=form.title.data, body=form.body.data)

        db.session.add(new_post)
        db.session.commit()

        return blog()
    return render_template('blog/create.html', form=form)


@blog_blueprint.route('/<int:id>/update', methods=('GET', 'POST'))
def update(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        return render_template('500.html')

    form = PostForm()

    if form.validate_on_submit():
        post.update_post(form.title.data, form.body.data)

    form.title.data = post.title
    form.body.data = post.body

    return render_template('blog/blog.html', form=form)


@blog_blueprint.route('/<int:id>/delete')
def delete(id):
    Post.query.filter_by(id=id).delete()
    db.session.commit()

    return blog()

main/views.py
from flask import Blueprint, render_template

main_blueprint = Blueprint('main', __name__, template_folder='templates')


@main_blueprint.route('/')
def index():
    return render_template('main/index.html')

users/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from users.forms import RegisterForm, LoginForm

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        print(request.form.get('username'))
        print(request.form.get('password'))
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


@users_blueprint.route('/login')
def login():
    form = LoginForm()
    return render_template('users/login.html', form=form)


@users_blueprint.route('/logout')
def logout():
    return render_template('users/logout.html')

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSC2031 Blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>

<style>
    .table {
        margin-left: auto;
        margin-right: auto;
    }
</style>

<section class="hero is-primary is-fullheight">

    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('main.index') }}" class="navbar-item">
                            Home
                        </a>
                        <a href="{{ url_for('blog.blog') }}" class="navbar-item">
                            Blog
                        </a>
                        <a href="{{ url_for('blog.create') }}" class="navbar-item" >
                            Create Post
                        </a>
                        <a href="{{ url_for('users.register') }}" class="navbar-item">
                            Register
                        </a>
                        <a href="{{ url_for('users.login') }}" class="navbar-item">
                            Login
                        </a>
                        <a href="{{ url_for ('users.logout') }}" class="navbar-item">
                            Log out
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</section>
</body>

</html>

templates/blog/blog.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h1 class="title is-1">Posts</h1>
        <div class="box">
            {% for post in posts %}
                <article class="media">
                    <div class="media-content">
                        <div class="content">
                            <h1>{{ post.title }}</h1>
                            <p>
                                <strong>{{ post.username }}</strong>
                                <small>{{ post.created.strftime('%d-%m-%Y') }}</small>
                                <br>
                                {{ post.body }}
                                <br>
                            <div id="navbarMenuHeroA" class="navbar-menu">
                                <div class="navbar-start">
                                    <a class="navbar-item" href="{{ url_for('blog.update', id=post.id) }}">Update</a>
                                    <a class="navbar-item" href="{{ url_for('blog.delete', id=post.id) }}">Delete</a>
                                </div>
                            </div>
                            </p>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/blog/create.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h3 class="title is-3">Create Post</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.title(class="input", placeholder="Title") }}
                        {% for error in form.title.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.body(class="textarea", placeholder="Body") }}
                        {% for error in form.body.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/blog/update.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h3 class="title is-3">Update Post</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.title(class="input") }}
                        {% for error in form.title.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control" >
                        {{ form.body(class="textarea") }}
                        {% for error in form.body.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}

{% block content %}
    
    <h1 class="title is-1">index</h1>

{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    
<div class="column is-5 is-offset-4">
        <h3 class="title is-3">Login</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.username(class="input", placeholder="Email") }}
                        {%  for error in form.username.errors %}
                            {{ error }}
                        {%  endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {%  for error in form.password.errors %}
                            {{ error }}
                        {%  endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered", value="Login") }}
                </div>
            </form>
        </div>
    </div>


{% endblock %}

templates/users/logout.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="title is-1">logout</h1>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.username(class="input", placeholder="Email") }}
                        {%  for error in form.username.errors %}
                            {{ error }}
                        {%  endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {%  for error in form.password.errors %}
                            {{ error }}
                        {%  endfor %}
                    </div>
                </div>
                 <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {%  for error in form.confirm_password.errors %}
                            {{ error }}
                        {%  endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered", value="Sign Up") }}
                </div>
            </form>
        </div>
    </div>


{% endblock %}